--- #YAML:1.0
name: MasonX-Request-WithApacheSession
version: 0.24
license: perl
distribution_type: module
requires:
  Apache::Cookie: 0
  Apache::Session: 1.54
  HTML::Mason: 1.16
recommends: {}
build_requires: {}
conflicts: {}
provides:
  MasonX::Request::WithApacheSession:
    file: lib/MasonX/Request/WithApacheSession.pm
    version: 0.24
  MasonX::Request::WithMultiSession:
    file: lib/MasonX/Request/WithMultiSession.pm
generated_by: Module::Build version 0.21
