# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MasonX-Request-WithApacheSession
version:      0.23
version_from: lib/MasonX/Request/WithApacheSession.pm
installdirs:  site
requires:
    Apache::Cookie:                0
    Apache::Session:               1.54
    HTML::Mason:                   1.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
