---
name: MasonX-Request-WithApacheSession
version: 0.31
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Add a session to the Mason Request object
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Apache::Session::Wrapper: 0.13
  HTML::Mason: 1.16
provides:
  MasonX::Request::WithApacheSession:
    file: lib/MasonX/Request/WithApacheSession.pm
    version: 0.31
  MasonX::Request::WithMultiSession:
    file: lib/MasonX/Request/WithMultiSession.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
