--- #YAML:1.0
name: MasonX-Request-WithApacheSession
version: 0.25
author:
  - Dave Rolsky, <autarch@urth.org>
abstract: Add a session to the Mason Request object
license: perl
requires:
  Apache::Cookie: 0
  Apache::Session: 1.54
  HTML::Mason: 1.16
provides:
  MasonX::Request::WithApacheSession:
    file: lib/MasonX/Request/WithApacheSession.pm
    version: 0.25
  MasonX::Request::WithMultiSession:
    file: lib/MasonX/Request/WithMultiSession.pm
generated_by: Module::Build version 0.23
